# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tristan White
email: oliver.tristan@gmail.com
description: Hi! My name is Tristan White, I'm a designer, developer and somewhat unicorn-like.
             I was born and raised in a small town in Denmark. Today I am proud to call myself a full-stack web developer. 
             I love making beautiful, yet practical websites and applications.
baseurl: "" # the subpath of your site, e.g. /blog
url: "//tristanwhite.info/" # the base hostname & protocol for your site
twitter_username: Triss90
github_username:  triss90405

# Build settings
markdown: kramdown
# paginate: 2
# paginate_path: "/articles/page:num/"
